# Generated by Django 4.2.15 on 2024-12-28 19:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("menu", "0003_remove_qrmenu_file_key_remove_qrmenu_qr_file_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="MenuFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file_key", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("order", models.IntegerField(default=0)),
                (
                    "menu",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="menu.qrmenu",
                    ),
                ),
            ],
            options={
                "db_table": "menu_file",
            },
        ),
    ]
