# Generated by Django 4.2.15 on 2024-12-28 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0003_remove_qrmenu_file_key_remove_qrmenu_qr_file_key"),
        ("menu_file", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menufile",
            name="menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="menu.qrmenu",
            ),
        ),
    ]
