# Generated by Django 4.2.17 on 2025-02-25 04:12

from django.db import migrations, models
import django.db.models.deletion
import seat.enums.status
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("branch", "0003_branch_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("area", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("count", models.IntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UNOCCUPIED", "UNOCCUPIED"),
                            ("OCCUPIED", "OCCUPIED"),
                            ("RESERVED", "RESERVED"),
                        ],
                        db_index=True,
                        default=seat.enums.status.SeatStatus["UNOCCUPIED"],
                        max_length=50,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="branch.branch",
                    ),
                ),
            ],
            options={
                "db_table": "seat",
            },
        ),
    ]
