repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0  # Use the latest stable version
    hooks:
      - id: black
        name: black
        language_version: python3
        exclude: '(^|/)(migrations|venv|docs|static|mail_template/templates)/'

  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
        exclude: '(^|/)(migrations|venv|docs|static|mail_template/templates)/'
