version: '3.9'

services:
  redis:
    image: "redis:7.4.1"
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=sqs,dynamodb,lambda,sns,secretsmanager,ses
      - AWS_DEFAULT_REGION=ap-south-1
      - DEBUG=1
      - LS_LOG=trace
      - PERSISTENCE=1
    volumes:
      - ./build/stack/localstack:/etc/localstack/init/ready.d
    command: >
      sh -c "/etc/localstack/init/ready.d/init-aws-resources.sh localstack &&
             docker-entrypoint.sh"

  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: druling
      POSTGRES_PORT: 5432
      POSTGRES_NAME: druling

  web:
    build:
      context: .
      dockerfile: build/stack/web/Dockerfile
    command: >
      sh -c "./build/stack/db/wait-for-db.sh db && 
             ./build/stack/web/init-web.sh web"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_NAME: druling
      DATABASE_USER: druling
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      LOCALSTACK_HOST: localstack
    depends_on:
      - db
      - redis
      - localstack
