version: '3.9'

services:
  redis:
    image: "redis:7.4.1"
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:2.2.0
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - SERVICES=sqs,dynamodb,lambda,sns,secretsmanager,ses
      - AWS_DEFAULT_REGION=ap-south-1
    volumes:
      - ./localstack_bootstrap:/etc/localstack/init/ready.d
    command: >
      sh -c "chmod +x /etc/localstack/init/ready.d/init-aws-resources.sh &&
             /etc/localstack/init/ready.d/init-aws-resources.sh &&
             docker-entrypoint.sh"

  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: druling

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "./wait-for-db.sh db && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:3000"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - localstack
