# Generated by Django 4.2.17 on 2025-01-09 16:40

from django.db import migrations, models
import django.db.models.deletion
import subscription.enums.subscription_status
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profile", "0003_alter_profile_img_url"),
        ("subscription_plan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("cancellation_date", models.DateField(blank=True, null=True)),
                ("next_billing_date", models.DateField(blank=True, null=True)),
                ("auto_renewal", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "draft"),
                            ("COMPLETED", "completed"),
                            ("IN_PROGRESS", "in_progress"),
                            ("FAILED", "failed"),
                        ],
                        default=subscription.enums.subscription_status.SubscriptionStatus[
                            "DRAFT"
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription_plan.subscriptionplan",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "subscription",
            },
        ),
    ]
