# Generated by Django 4.2.15 on 2024-12-02 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="type",
        ),
    ]
