# Generated by Django 4.2.15 on 2025-01-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="img_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
