# Generated by Django 4.2.17 on 2025-01-07 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("subscription", "0001_initial"),
        ("profile", "0003_alter_profile_img_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.IntegerField()),
                ("discount", models.IntegerField(default=0)),
                ("taxes", models.IntegerField(default=0)),
                ("total_amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("COMPLETED", "completed"),
                            ("IN_PROGRESS", "in_progress"),
                            ("CANCELLED", "cancelled"),
                            ("FAILED", "failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("method", models.CharField(max_length=50)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "-created_at"],
                        name="transaction_profile_934a6d_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="transaction_status_c83f11_idx",
                    ),
                ],
            },
        ),
    ]
