# Generated by Django 4.2.17 on 2025-02-08 06:35

from django.db import migrations, models
import django.db.models.deletion
import transaction.enums.transaction_status
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profile", "0003_alter_profile_img_url"),
        ("subscription", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.IntegerField()),
                ("discount", models.IntegerField(default=0)),
                ("taxes", models.IntegerField(default=0)),
                ("total_amount", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "COMPLETED"),
                            ("pending", "PENDING"),
                            ("cancelled", "CANCELLED"),
                            ("failed", "FAILED"),
                        ],
                        default=transaction.enums.transaction_status.TransactionStatus[
                            "PENDING"
                        ],
                        max_length=50,
                    ),
                ),
                ("method", models.CharField(blank=True, max_length=50, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reference_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
                (
                    "subscription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction",
                        to="subscription.subscription",
                    ),
                ),
            ],
            options={
                "db_table": "transaction",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["profile", "-created_at"],
                        name="transaction_profile_934a6d_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="transaction_status_c83f11_idx",
                    ),
                ],
            },
        ),
    ]
