# Generated by Django 4.2.17 on 2025-02-08 06:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plan", "0001_initial"),
        ("profile", "0003_alter_profile_img_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("QR_MENU", "qr_menu")], db_index=True, max_length=50
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("limit", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plan.plan"
                    ),
                ),
            ],
            options={
                "db_table": "feature",
            },
        ),
        migrations.CreateModel(
            name="ProfileFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("QR_MENU", "qr_menu")], db_index=True, max_length=50
                    ),
                ),
                ("limit", models.IntegerField(default=0)),
                ("usage", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profile.profile",
                    ),
                ),
            ],
            options={
                "db_table": "profile_feature",
                "indexes": [
                    models.Index(
                        fields=["profile", "type"], name="prof_feature_profile_type_idx"
                    )
                ],
            },
        ),
    ]
