# Generated by Django 4.2.15 on 2025-01-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="img_url",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
