# Generated by Django 4.2.15 on 2024-12-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contact_deleted_at"),
        ("restaurant", "0002_restaurant_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="restaurant",
                to="contact.contact",
            ),
        ),
    ]
