# Generated by Django 4.2.17 on 2025-02-08 06:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("duration", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product",
                    models.CharField(
                        choices=[("menu", "menu")], db_index=True, max_length=50
                    ),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("BASIC", "basic"),
                            ("ADVANCE", "advance"),
                            ("PREMIUM", "premium"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
            ],
            options={
                "db_table": "plan",
                "indexes": [
                    models.Index(
                        fields=["product", "plan_type"],
                        name="plan_product_plan_type_idx",
                    )
                ],
            },
        ),
    ]
