# Generated by Django 4.2.17 on 2025-02-05 15:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("amount", models.IntegerField()),
                ("name", models.CharField(max_length=50)),
                ("duration", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "plan",
            },
        ),
    ]
