# Generated by Django 4.2.15 on 2024-12-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0002_contact_deleted_at"),
        ("social_contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialcontact",
            name="contact",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="socials",
                to="contact.contact",
            ),
        ),
    ]
