# Generated by Django 4.2.15 on 2024-12-28 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_qrmenu_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qrmenu",
            name="file_key",
        ),
        migrations.RemoveField(
            model_name="qrmenu",
            name="qr_file_key",
        ),
    ]
