# Generated by Django 4.2.15 on 2024-12-29 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0004_branch_description"),
        ("menu", "0003_remove_qrmenu_file_key_remove_qrmenu_qr_file_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrmenu",
            name="branch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="branch.branch",
            ),
        ),
    ]
