# Generated by Django 4.2.15 on 2024-12-31 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0004_branch_description"),
        ("menu", "0004_alter_qrmenu_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrmenu",
            name="branch",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="menu",
                to="branch.branch",
            ),
        ),
    ]
