# Generated by Django 4.2.15 on 2024-12-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0006_alter_qrmenu_branch"),
    ]

    operations = [
        migrations.AddField(
            model_name="qrmenu",
            name="theme",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
