# Generated by Django 4.2.17 on 2025-01-07 16:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("plan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceLimit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("QR_MENU", "qr_menu"),
                            ("IN_PROGRESS", "in_progress"),
                            ("CANCELLED", "cancelled"),
                            ("FAILED", "failed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("limit", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "plan_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plan.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "resource_limit",
            },
        ),
    ]
