# Generated by Django 4.2.15 on 2024-12-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0003_alter_branch_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
