# Generated by Django 4.2.15 on 2024-12-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("entity_relation", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityrelation",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
