# Generated by Django 4.2.15 on 2024-12-16 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("branch", "0003_alter_branch_contact"),
        ("profile", "0004_profile_deleted_at_alter_profile_contact_and_more"),
        ("entity_relation", "0003_entityrelation_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entityrelation",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="relations",
                to="branch.branch",
            ),
        ),
        migrations.AlterField(
            model_name="entityrelation",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="profile.profile"
            ),
        ),
    ]
