# Generated by Django 4.2.17 on 2025-02-02 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlockedEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_index=True,
                        max_length=254,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("permanent", "PERMANENT"),
                            ("temporary", "TEMPORARY"),
                            ("unblocked", "UNBLOCKED"),
                        ],
                        max_length=50,
                    ),
                ),
                ("count", models.IntegerField(default=1)),
            ],
            options={
                "db_table": "blocked_email",
            },
        ),
    ]
