# Generated by Django 4.2.17 on 2025-02-25 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("seat", "0001_initial"),
        ("item", "0002_addon_itemvariation_itemaddon"),
        ("order", "0001_initial"),
        ("branch", "0003_branch_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="seatorder",
            name="seat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="seat.seat",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="addon",
            field=models.ManyToManyField(blank=True, to="item.itemaddon"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="addons",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_item",
                to="item.item",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="item.item"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="variation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="item.itemvariation",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="branch.branch",
            ),
        ),
    ]
